export {default as Navigation} from "./Navigation/navigation"
export {default as Sidebar} from "./Sidebar/sidebar"
export {default as Footer} from "./Footer/footer"
export {default as OurServices} from "./Services/eachservice"
export {default as Testimonial} from "./Testimonial/testimonial"
export {default as Banner} from "./Banner/banner"